RISCV_PREFIX   ?= riscv32-unknown-elf-
RISCV_GCC      ?= $(RISCV_PREFIX)gcc
RISCV_OBJDUMP  ?= $(RISCV_PREFIX)objdump
RISCV_OBJCOPY  ?= $(RISCV_PREFIX)objcopy
RISCV_READELF  ?= $(RISCV_PREFIX)readelf
RISCV_GCC_OPTS ?= -static -mcmodel=medany -g -fvisibility=hidden -nostdlib -nostartfiles -DXLEN=$(XLEN) $(RVTEST_DEFINES)

COMPILE_CMD=\
	$$(RISCV_GCC) $(1) $$(RISCV_GCC_OPTS) \
		-I$(ROOTDIR)/riscv-test-suite/env/ \
		-I$(TARGETDIR)/$(RISCV_TARGET)/ \
		-T$(TARGETDIR)/$(RISCV_TARGET)/link.ld $$< \
		-o $$@; \
	$$(RISCV_OBJCOPY) -j .text -O binary $$@ $$@_if.bin; \
	$$(RISCV_OBJCOPY) -j .data -O binary $$@ $$@_ls.bin

OBJ_CMD = $$(RISCV_OBJDUMP) $$@ -D > $$@.objdump; \
		  $$(RISCV_OBJDUMP) $$@ --source > $$@.debug; \
		  $$(RISCV_READELF) -a $$@ > $$@.readelf

COMPILE_TARGET=\
	    $(COMPILE_CMD); \
        if [ $$$$? -ne 0 ] ; \
            then \
            echo "\e[31m$$(RISCV_GCC) failed for target $$(@) \e[39m" ; \
            exit 1 ; \
        fi ; \
	    $(OBJ_CMD); \
        if [ $$$$? -ne 0 ] ; \
            then \
            echo "\e[31m $$(RISCV_OBJDUMP) failed for target $$(@) \e[39m" ; \
            exit 1 ; \
        fi ;

RUN_TARGET=\
	cp $(*).elf_if.bin $(TARGETDIR)/../sim/mem_if.bin; \
    cp $(*).elf_ls.bin $(TARGETDIR)/../sim/mem_ls.bin; \
	cd $(TARGETDIR)/../sim/; \
	make -f Makefile.verilator; \
	cp signature.txt $(*).signature.output
