= Address mask
:toc:

== Introduction

The aim is to generalize the idea of limiting the address space to less than XLEN address bits.
The address mask would be applied to both the instruction fetch unit (IFU)
program counter (PC) and load/store unit (LSU).
This approach matches the common practice of implementing the system bus with partial decoding of the address.

Advantages:

* The mask cuts off the adder cary propagation from covering the entire XLEN, thus improving timing.
* The masked parts don't require adder logic or flip-flops, thus reducing area.
* The masks do not inherently reduce toggling, but some power savings can be expected
  from the area and timing improvements.

Disadvantages:

* Extra consideration is required to not introduce issues.
  This can be solved with automatic parameter validation for system bus components
  and additionally with `X` propagation for masked address bits during simulation.

Considerations:

* overview of partial decoding approaches,
* review all RISC-V PC related instructions,
* review all RISC-V load/store (memory) instructions,
* review of RISC-V trap handling,
* review of RISC-V memory protection unit (MPU), memory management unit (MMU),
* RISCOF related considerations (tests, reference simulators),
* C compiler considerations (GCC, LVVM, ...).

Implementation:

* Special timing constrains on shared resources (`set_case_analysis`)?

=== Signed/unsigned immediate masked addition

A signed/unsigned immediate `simm`/`uimm` of width `IMMW < XLEN`
is sign/zero extended to create `imm` of width `XLEN`.
This is added to a base value `val` of width `XLEN`
to produce the resulting `sum` of width `XLEN`.
A mask `MASK` of width `XLEN` is used to mask a subset of signals `val`, `imm` and `sum`.

[source,verilog]
----
parameter logic [XLEN-1:0] MASK;

logic unsigned [IMMW-1:0] uimm;
logic   signed [IMMW-1:0] simm;

logic [XLEN-1:0] imm;
logic [XLEN-1:0] val;
logic [XLEN-1:0] sum;

// zero/sign extended immediate
case (signedness)
    UNSIGNED: imm = $unsigned(uimm) = { {XLE-IMMW{1'b0        }}, uimm };
      SIGNED: imm =   $signed(simm) = { {XLE-IMMW{simm[IMMW-1]}}, simm };
endcase
----

[%autowidth]
|===
| `sum` | `val` | `imm` | adder                             | address (or `PC` register)
|       |       |       | `sum = (val        + imm       )` | `addr = sum`
|       |       | MASK  | `sum = (val        + imm & MASK)` | `addr = sum`
|       | MASK  |       | `sum = (val & MASK + imm       )` | `addr = sum`
|       | MASK  | MASK  | `sum = (val & MASK + imm & MASK)` | `addr = sum`
| MASK  |       |       | `sum = (val        + imm       )' | `addr = sum & MASK`
| MASK  |       | MASK  | `sum = (val        + imm & MASK)' | `addr = sum & MASK`
| MASK  | MASK  |       | `sum = (val & MASK + imm       )' | `addr = sum & MASK`
| MASK  | MASK  | MASK  | `sum = (val & MASK + imm & MASK)' | `addr = sum & MASK`
|===

As an universal solution, both operands can be masked,
and additionally the sum would also be masked before being used as an address.

Since adders resources can be shared to operate on different arguments for different instructions,
a mask can add unnecessary resources to an implementation.
Therefore masking both operands and the result might not be the obvious choice for all use cases.

I can't think of a use case, where masking the result of the addition
while converting it into an address (or `PC` register) would require additional resources.

The carry can be prevented from propagating further than bit `[i]`
if for both addition operands bit `[i]` is zero.
Depending on operand values withing the range `[i-1:0]`,
the carry can still propagate into the results bit `[1]`.

All this means a different approach might give better results
depending on whether the immediate is sign or zero extended.
Further research might provide a universal solution,
or it could be possible each RISC-V implementation
would have to go through a set of considerations.

=== RISC-V architecture used for considerations

The architecture used for considerations is using 2 adders (`PC` and `ALU`) to implement all instructions.

All `LOAD`/`STORE` instructions use the `ALU` adder to calculate the data address.
The `PC` adder is used to increment the PC and the instruction address.

All `BRANCH` instructions use the `ALU` adder to calculate the condition for the branch to be taken.
The `PC` adder is used to either increment the PC and the instruction address,
or add the branch offset.

Instructions `JAL`/`JALR` use the `ALU` adder to calculate the jump address and new `PC`.
While the `PC` adder is used to calculate the link address.

This can be seen as a role inversion for the two adders,
the choice was made to be able to have simple `PC` adder
implemented as a RCA with 12 full adders (branch immediate size)
while the remaining XLEN-12 bits are a potentially simpler incrementer/decrementer.

== IFU (PC)

The examples are for a RV32 processor (`XLEN=32`).
The RAM/ROM sizes are similar to small microcontrollers on the market.
The few microcontrollers I looked into also have a full 32-bit address space with sparse contents,
meaning LSB address bits are used to decode within memory/peripheral sections
and MSB address bits are used to decode the choice of section.

The address space used for examples is similar to what RISC-V simulators `spike` and `sail` use.
There is a 4kB ROM at address `0x00000000` and a 64kB RAM at address `0x80000000`.
The reset address is set to `0x00000000`.

NOTE: I was thinking of adding an XIP SPI Flash,
      but those flash devices are in the range of 8MB~128MB,
      so very few address bits would be unused
      thus missing the point of address masking.

.IFU address space
[%autowidth]
|===
| address                     | memory
| `0x00000000` ~ `0x00000fff` | boot ROM 4kB (`2**12`)
| `0x00010000` ~ `0x7fffffff` | boot ROM (`2**(32-1-12)-1` partially decoded copies)
| `0x80000000` ~ `0x8000ffff` | instruction RAM 64kB (`2**16`)
| `0x80010000` ~ `0xffffffff` | instruction RAM (`2**(32-1-16)-1` partially decoded copies)
|===

Two parameters are used to define the reset address and mask.

.IFU parameters
[%autowidth]
|===
| parameter   | value        | description
| `IFU_RESET` | `0x00000000` | IFU reset address, PC reset value
| `IFU_MASK`  | `0x8000FFFF` | IFU address and PC mask
|===

The PC `pc` points to the currently executing instruction `op`.
The IFU address `ifu_addr` points to the next instruction.
The current instruction size in bytes is `ilen`.

The Verilog based pseudocode is a bit simplified,
for example the case where `op` is a branch, the branch is taken.

The IFU address is a combinational assignment.
The PC is synchronously loaded with the IFU address.

.IFU implementation without masking (simplified code)
[source,verilog]
----
// IFU address
always_comb
case (op)
    JAL    : ifu_addr = pc + imm_j;   // signed offset[20:1]
    JALR   : ifu_addr = rs1 + imm_i;  // signed offset[11:0]
    BRANCH : ifu_addr = pc + imm_b;   // signed offset[12:1]
    TRAP   : ifu_addr = csr_tvec;
    default: ifu_addr = pc + ilen;
endcase

// link GPR
always_ff @(posedge clk)
case (op)
    JAL    : rd <= pc + ilen;
    JALR   : rd <= pc + ilen;
endcase

// xEPC CSR

// program counter
always_ff @(posedge clk, posedge rst)
if (rst) pc <= IFU_RESET;
else     pc <= ifu_addr;
----

=== Instructions incrementing `PC` by `ILEN`

The mask is applied to the `PC` while calculating the IFU address.
No masking is applied to the unsigned `ilen`, at least not in a reasonably configured system.
Each `0` bit in the mask will prevent carry propagation.
`PC` MSB bits (any bits beyond the first `0` in the mask) will not change,
and would not be affected by carry propagation timing.

.Instructions incrementing PC by `ILEN` with masking
[source,verilog]
----
ifu_addr = (pc & IFU_MASK + ilen) & IFU_MASK;

always_ff @(posedge clk, posedge rst)
if (rst) pc <= IFU_RESET;
else     pc <= (ifu_addr & IFU_MASK) | (IFU_RESET & ~IFU_MASK);
----

As long as the `PC` is within it based decoded memory region,
the behavior matches a maskless system.

While it would be possible to create an assembly program crossing the barrier
between the base and partially decoded copies (something like loop unwinding),
I doubt a compiler would create such code.
In such a case, after the execution would reach the end of the partially decoded memory
it would wrap to its beginning.
In a masked system, the `PC` would also wrap, while in an maskless system it would continue incrementing.

=== Branch instructions

For the IFU address calculation the mask is applied to both the `PC`
and the 12-bit signed branch immediate.
Each `0` bit in the mask beyond index 12 will prevent carry propagation.

.Branch instructions with masking
[source,verilog]
----
// version which allows a late taken signal, but implements two adders
ifu_addr = (taken) ? (pc & IFU_MASK + imm_b & IFU_MASK) & IFU_MASK
                   : (pc & IFU_MASK + ilen            ) & IFU_MASK;

// version with a single adder, but adds the adder delay to the taken delay
ifu_addr = (pc & IFU_MASK + (taken) ? imm_b & IFU_MASK : ilen) & IFU_MASK;

always_ff @(posedge clk, posedge rst)
if (rst) pc <= IFU_RESET;
else     pc <= (ifu_addr & IFU_MASK) | (IFU_RESET & ~IFU_MASK);
----

Same reasoning as for incrementing `PC` by `ILEN`.
As long as 12+1 LSB mask bits are `1`, there is also no possibility
of a branch moving execution between separate partially decoded memory blocks.

=== JAL

Both the `pc` and the 20-bit sign extended offset are masked.
Each `0` bit in the mask beyond index 21 will prevent carry propagation.

.JAL with masking
[source,verilog]
----
ifu_addr = (pc & IFU_MASK + imm_j & IFU_MASK) & IFU_MASK;   // signed offset[20:1]

always_ff @(posedge clk)
rd <= (pc & IFU_MASK + ilen) & IFU_MASK;  // link

always_ff @(posedge clk, posedge rst)
if (rst) pc <= IFU_RESET;
else     pc <= (ifu_addr & IFU_MASK) | (IFU_RESET & ~IFU_MASK);
----

=== JALR

Both the `rs1` and the 12-bit sign extended offset are masked.
Each `0` bit in the mask beyond index 12 will prevent carry propagation.

.JALR with masking
[source,verilog]
----
ifu_addr = (rs1 & IFU_MASK + imm_i & IFU_MASK) & IFU_MASK;   // signed offset[11:0]

always_ff @(posedge clk)
rd <= (pc & IFU_MASK + ilen) & IFU_MASK;  // link

always_ff @(posedge clk, posedge rst)
if (rst) pc <= IFU_RESET;
else     pc <= (ifu_addr & IFU_MASK) | (IFU_RESET & ~IFU_MASK);
----

=== TRAPS

Trap related registers would have fewer nonzero bits.

== LSU

In addition to the memories, the LSU address space contains peripherals 

.IFU address space
[%autowidth]
|===
| address                     | memory
| `0x00000000` ~ `0x00000fff` | boot ROM 4kB (`2**12`)
| `0x00010000` ~ `0x7fffffff` | boot ROM (`2**(32-1-12)-1` partially decoded copies)
| `0x80000000` ~ `0x8000ffff` | instruction RAM 64kB (`2**16`)
| `0x80010000` ~ `0x80010fff` | peripherals 4kB (`2**12`)
| `0x80011000` ~ `0x8001ffff` | peripherals 4kB (`2**(16-12)-1` partially decoded copies)
| `0x80020000` ~ `0xffffffff` | instruction RAM and partially decoded peripherals 128kB (`2**(32-1-17)-1` partially decoded copies)
|===

Parameter are used to define the address mask.
Compared to the IFU address space one more bit is unmasked.

.LSU parameters
[%autowidth]
|===
| parameter   | value        | description
| `LSU_MASK`  | `0x8001FFFF` | IFU address and PC mask
|===

The full implementation requires a full 32-bit carry chain propagation
to calculate the MSB address bit.

.load/store without masking
[source,verilog]
always_comb
case (op)
    LOAD : lsu_addr = rs1 + imm_j;
    STORE: lsu_addr = rs1 + imm_s;
endcase

By applying the mask the carry propagation is blocked.

.load/store with masking
[source,verilog]
always_comb
case (op)
    LOAD : lsu_addr = (rs1 & LSU_MASK + imm_j) & LSU_MASK;
    STORE: lsu_addr = (rs1 & LSU_MASK + imm_s) & LSU_MASK;
endcase

A different approach would also be possible,
where the unmasked part of the address would come from addition,
while the masked part of the address would come directly from `rs1`.

There would be advantages and disadvantages to this approach.

.load/store alternative masking
[source,verilog]
always_comb
case (op)
    LOAD : lsu_addr = (rs1 & ~LSU_MASK) | (rs1 & LSU_MASK + imm_j) & LSU_MASK;
    STORE: lsu_addr = (rs1 & ~LSU_MASK) | (rs1 & LSU_MASK + imm_s) & LSU_MASK;
endcase

== References

QUAD SPI Flash for XIP:
https://www.infineon.com/cms/en/product/memories/nor-flash/serial-nor-flash/quad-spi-flash/

CH32V003 microcontroller:
https://www.wch-ic.com/downloads/CH32V003DS0_PDF.html