= R5P Mouse processor

== Introduction

The main feature of this processor is storing GPR
in the same memory as instructions and data,
instead of having a dedicated register file.

This approach can be used in small FPGA to avoid the overhead,
when the GPR register file would consume less than the entire memory block size.
For FPGA families without some kind of distributed memory with asynchronous read
to be used for the GPR register file,
this approach avoids using logic cell registers for GPR.

On ASIC this enables the creation of a processor
around a single single-port SRAM memory.
Thus having the smallest possible memory cell for GPR.

This approach looses some of the RISC architecture advantages,
when there is a fast GPR register file compared to a slower memory.
The advantage of simultaneous 2R1W GPR and memory access is also lost.

Performance aside, this processor can still take full advantage
of the RISC-V toolchain compared to a fully custom solution,
which would also require a custom toolchain.

The CPU takes multiple clock cycles to execute an instruction.
Most this cycles are used to perform a system bus access to either
fetch an instruction, read/write to GPR or memory/peripheral load/store.
The only exception are BRANCH instructions.

The system bus interface is designed around the SRAM interface.
If peripherals behave the same, then each system bus access takes
a single clock cycle.

== Instruction execution phases

Phases have a similar meaning as pipeline stages,
but the word stage is not used, since there is no pipelining parallelism.
Instead, the same logic is used in each phase to perform a different task.
For example a single adder is shared across all stages.

.Instruction execution phase names
[%autowidth]
|===
| Phase | Description
| IF    | Instruction fetch.
| RS1   | Read register source 1.
| RS2   | Read register source 1.
| LD    | Memory load.
| ST    | Memory store.
| EXE   | Execute (only used to evaluate branching condition).
| WB    | GPR write-back.
|===

What would usually be called execute (EXE) is part of either LD/ST or WB.

Instructions take between 1 and 4 clock cycles to execute, depending on the instruction.
The CPU state machine has 4 states, each phase fits into one of those states.
Instructions do not need all available phases
so multiple similar phases can share the same state.

Phase 0 always performs an instruction fetch,
phase 1 always follows phase 0, since the instruction can't be decoded earlier.
Other states always follow in order as numbered, but some can be skipped,
they have more variability regarding which phase they contain.

The basic sequence of states/phases depends on the opcode
(see the _RISC-V base opcode map_ in the _The RISC-V Instruction Set Manual Volume I_).

.Sequence of instruction execution phases for each opcode
[%autowidth]
|===
|  opcode     | encoding | instructions                                                           | state 0 | state 1 | state 2 | state 3 | total | notes

| `LOAD`      | I-type   | `LB`, `LH`, `LW`, `LBU`, `LHU`                                         | `IF`    | `RS1`   | `MLD`   | `WB`    | 4     |
| `OP_IMM_32` | I-type   | `ADDI`, `SLTI`, `SLTIU`, `XORI`, `ORI`, `ANDI`, `SLLI`, `SRLI`, `SRAI` | `IF`    | `RS1`   |         | `WB`    | 3     |
| `AUIPC`     | U-type   | `AUIPC`                                                                | `IF`    | `WB`    |         |         | 2     |
| `STORE`     | S-type   | `SB`, `SH`, `SW`                                                       | `IF`    | `RS1`   | `RS2`   | `MST`   | 4     |
| `OP_32`     | R-type   | `ADD`, `SUB`, `SLL`, `SLT`, `SLTU`, `XOR`, `SRL`, `SRA`, `OR`, `AND`   | `IF`    | `RS1`   | `RS2`   | `WB`    | 4     |
| `LUI`       | U-type   | `LUI`                                                                  | `IF`    | `WB`    |         |         | 2     |
| `BRANCH`    | B-type   | `BEQ`, `BNE`, `BLT`, `BGE`, `BLTU`, `BGEU`                             | `IF`    | `RS1`   | `RS2`   | `EXE`   | 4     |
| `JALR`      | I-type   | `JALR`                                                                 | `IF`    | `RS1`   |         | `WB`    | 3     |
| `JAL`       | J-type   | `JAL`                                                                  | `IF`    | `WB`    |         |         | 2     |
| `SYSTEM`    |          | `ECALL`, `EBREAK`                                                      | `IF`    | `???`   |         |         | ???   | TODO
| `MISC_MEM`  |          | `FENCE`, `PAUSE`                                                       | `IF`    | `NOP`   |         |         | 2     | TODO
|===

=== IF phase (instruction fetch)

All instructions require this phase.

The PC value is on the system address bus,
so in the next phase the system read data bus will have the instruction opcode.
For all further states/phases, the opcode is stored in the instruction buffer.

The address depends on the previous instruction opcode,
a branch (BRANCH), a jump (JAL, JALR) or a simple increment (other opcodes).

The reset sequence starts as if the previous instruction was
a jump to the reset address (`JAL x0, reset`).

=== RS1 phase (read register source 1)

The GPR register source 1 (`rs1`) index is available
by decoding the instruction opcode and placed on the system address bus.
In the next phase the system read data bus will have the `rs1` contents.
For all further states/phases, the `rs1` contents will be stored in the data buffer.

=== RS2 phase (read register source 2)

The GPR register source 2 (`rs2`) index is available
by decoding the buffered instruction opcode and placed on the system address bus.
In the next phase the system read data bus will have the `rs2` contents.
There is no need to store this value for later phases.

=== LD phase (load)

The load immediate is available by decoding the buffered instruction opcode,
it is added to the `rs1` value from the system read data bus
and placed on the system address bus.
In the next phase the system read data bus will have the load contents.

=== ST phase (store)

The store immediate is available by decoding the buffered instruction opcode,
it is added to the `rs1` value from the data buffer
and placed on the system address bus.
The `rs1` value is available on the system read data bus (see RS2 phase)
and placed on the system write data bus.

=== WB phase (write-back)

GPR destination register (`rd`) index is available as part of the opcode,
and placed on the system address bus.
The write back value is either available on the system read data bus
due to the previous phase, or calculated by an ALU operation,
and is placed on the system write data bus.

This is always the last phase.

== Instruction execution details

This section provides further details on how signal values propagate between phases.
The following tables list signals and values and describes each.
Then subsections cover each opcode in more details.

The following system bus signals are observed:

.System bus signals
[%autowidth]
|===
| signal    | description
| `bus_adr` | address
| `bus_wdt` | write data
| `bus_rdt` | read data
|===

.Internal signals
[%autowidth]
|===
|===

System bus and internal signals can have different values
depending on the opcode and phase, most options are listed here.

| `dec_rs1` | decoder GPR `rs1` address |
| `dec_rs2` | decoder GPR `rs2` address |
| `dec_rd`  | decoder GPR `rd`  address |
| `dec_imi` | decoder immediate I (integer, load) |
| `dec_imb` | decoder immediate B (branch) |
| `dec_ims` | decoder immediate S (store) |
| `gpr_rs1` | GPR `rs1` data |
| `gpr_rs2` | GPR `rs2` data |
| `alu_add` | ALU adder |
| `inw`     | instruction Operation Code |
| `inw_buf` |
| `buf_dat` |

=== R-type

Arithmetic (`ADD`, `SUB`) and logical (`OR`, `AND`, `XOR`) operations.

| cycle     | `alu_add` | `bus_adr` | `bus_wdt` | `bus_rdt` | data buffer | description |
|-----------|-----------|-----------|-----------|-----------|-------------|-------------|
| fe        |   PC+4    | `alu_add` |           |           |             | instruction fetch |
| rs1       |           | `dec_rs1` |           | `inw`     |             | read register source 1 |
| rs2       |           | `dec_rs2` |           | `gpr_rs1` | instr. op.  | read register source 2 |
| wb,ex     | `rs1+rs2` | `dec_rd`  | `alu_add` | `gpr_rs2` | rs1 data    | execute and write-back |

In the last phase, the ALU is used for summation or a logical operation
between `rs1` data (in the data buffer) and `rs2` (on the read data bus).
The ALU output is placed on the write data bus for write-back.

The `rd` address must be stored in a dedicated register,
since the data buffer looses the instruction opcode
in the previous phase.

=== I-type

| cycle     | `alu_add` | `bus_adr` | `bus_wdt` | `bus_rdt` | data buffer | description |
|-----------|-----------|-----------|-----------|-----------|-------------|-------------|
| fe        |   PC+4    | `alu_add` |           |           |             | instruction fetch |
| rs1       |           | `dec_rs1` |           | `inw`     |             | read register source 1 |
| wb,ex     | `rs1+imi` | `dec_rd`  | `alu_add` | `gpr_rs2` | rs1 data    | execute and write-back |

For I-type instructions there is no need to read `rs2` contents,
so this phase can be skipped.

In the last phase, the ALU is used for summation or a logical operation
between `rs1` data (on the read data bus) and an immediate
(from the instruction opcode inside the data buffer).
The ALU output is placed on the write data bus for write-back.

The `rd` address is decoded from the instruction opcode inside the data buffer.
NOTE: a better alternative is to use the same dedicated register as for R-type.

=== JALR

| cycle     | `alu_add` | `bus_adr` | `bus_wdt` | `bus_rdt` | data buffer | description |
|-----------|-----------|-----------|-----------|-----------|-------------|-------------|
| fe        |   PC+4    | `alu_add` |           |           |             | instruction fetch |
| rs1       |           | `dec_rs1` |           | `inw`     |             | read register source 1 |
| wb,ex     |   PC+4    | `dec_rd`  | `alu_add` | `gpr_rs2` | rs1 data    | execute and write-back |
|-----------|-----------|-----------|-----------|-----------|-------------|-------------|
| fe        | ` PC+buf` | `alu_add` |           |           |             | instruction fetch |

=== L-type (I-type load)

| cycle     | `alu_add` | `bus_adr` | `bus_wdt` | `bus_rdt` | data buffer | description |
|-----------|-----------|-----------|-----------|-----------|-------------|-------------|
| fe        |   PC+4    | `alu_add` |           |           |             | instruction fetch |
| rs1       |           | `dec_rs1` |           | `inw`     |             | read register source 1 |
| ld        | `rs1+imi` | `alu_add` |           | `gpr_rs2` | `dimm`      | load |
| wb        |           | `dec_rd`  | `bus_rdt` |           |             | write-back |

For I-type instructions there is no need to read `rs2` contents,
so this phase can be skipped.

In the execute and load phase,
the ALU is used to calculate the memory load address from
`rs1` data (on the read data bus) and an immediate
(from the instruction opcode inside the data buffer).

In the last phase the read data bus value is copied
to the write data bus for write-back.
The `rd` address must be stored in a dedicated register,
since the data buffer looses the instruction opcode
in the previous phase.

=== S-type

| cycle     | `alu_add` | `bus_adr` | `bus_wdt` | `bus_rdt` | buffer    | description |
|-----------|-----------|-----------|-----------|-----------|-----------|-------------|
| fe        |   PC+4    | `alu_add` |           |           |           | instruction fetch |
| rs1       |           | `dec_rs1` |           | `inw`     |           | read register source 1 |
| rs2       | `rs1+ims` | `dec_rs2` |           | `gpr_rs1` | `dec_ims` | read register source 2 |
| wb        |           | `buf_dat` | `bus_rdt` | `gpr_rs1` | `alu_add` | write-back |

TODO: leaving table here, since it uses adder in same stage as load,


| phase     | address      | read data   | data buffer | write data     | description |
|-----------|--------------|-------------|-------------|----------------|-------------|
| fe        | PC           |             |             |                | instruction fetch |
| rs1       | rs1 addr.    | instr. op.  |             |                | read register source 1 |
| rs2,ex    | rs2 addr.    | rs1 data    | instr. op.  |                | read register source 2 and execute |
| st        | data buffer  | rs2 data    | ALU result  | read data      | store to memory |

The execute phase is the same as in the L-type,
the calculated ALU output is the store address and
is placed into the data buffer, to be used in the next phase.

In the last phase, read data is copied to write data and
written to memory at the address calculated in the previous phase.

=== B-type

| cycle     | `alu_add` | `bus_adr` | `bus_wdt` | `bus_rdt` | data buffer | description |
|-----------|-----------|-----------|-----------|-----------|-------------|-------------|
| fe        |   PC+imb  | `alu_add` |           |           |             | instruction fetch with branch |
| rs1       |           | `dec_rs1` |           | `inw`     |             | read register source 1 |
| rs2       |           | `dec_rs2` |           | `gpr_rs1` | instr. op.  | read register source 2 |
| wb,ex     | `rs1+rs2` |           |           | `gpr_rs2` | rs1 data    | execute |

| cycle     | address      | read data   | data buffer | rd addr. | write data | description |
|-----------|--------------|-------------|-------------|----------|------------|-------------|
| fe        |   PC+imb           |             |             |          |            | instruction fetch |
| rs1       | rs1 addr.    | instr. op.  |             |          |            | read register source 1 |
| rs2       | rs2 addr.    | rs1 data    | instr. op.  |          |            | read register source 2 and execute |
| ex        | rd  addr.    | rs2 data    | rs1 data    |          |            | execute and write-back |

Similar to R-type but instead of a write back,
The ALU result is used as a branch taken condition.

TODO: in the 3-rd phase the ALU could be used to calculate the branch address,
the result stored somewhere and in the last phase loaded into the PC.
As an alternative, the branch immediate could be stored in an extended version of
`rd` addr. buffer and used to calculate the new PC with a dedicated adder.

NOTE: since there is no memory access in the 4-th phase,
this phase could be combined into the next fetch,
but this would affect timing significantly.

=== U-type

| cycle     | address      | read data   | data buffer | rd addr. | write data | description |
|-----------|--------------|-------------|-------------|----------|------------|-------------|
| fe        | PC           |             |             |          |            | instruction fetch |
| ex,wb     | rd  addr.    | rs2 data    | rs1 data    |          | ALU result | execute and write-back |

`rd` address is extracted directly from read data.

TODO

=== J-type

JAL

| cycle     | `alu_add` | `bus_adr` | `bus_wdt` | `bus_rdt` | data buffer | description |
|-----------|-----------|-----------|-----------|-----------|-------------|-------------|
| fe        |   PC+4    | `alu_add` |           |           |             | instruction fetch |
| wb,ex     |   PC+4    | `dec_rd`  | `alu_add` | `gpr_rs2` | rs1 data    | execute and write-back |
|-----------|-----------|-----------|-----------|-----------|-------------|-------------|
| fe        | ` PC+buf` | `alu_add` |           |           |             | instruction fetch |


| cycle     | address      | read data   | data buffer | rd addr. | write data | description |
|-----------|--------------|-------------|-------------|----------|------------|-------------|
| fe        | PC           |             |             |          |            | instruction fetch |
| TODO      | rd  addr.    |             |             |          |            |  |

TODO



== System bus

The buffer contains a copy of the read data bus on the previous cycle.

If the GPR register file is stored at the end of the address space,
than the address of a register `gpr[4:0]` would be `{{XLEN-5{1'b1}}, gpr[4:0]}`.

In case the same ALU is used for R-type and LOAD/STORE operations,
there is not much advantage to having an address bus of less than XLEN.

The PC adder for increments and branches can be shorter to save logic.
The PC is unsigned extended to XLEN for the address bus.


| state | phases     | address      | read data   | data buffer | write data     | description |
|-------|------------|--------------|-------------|-------------|----------------|-------------|
| `ST0` | IFD        | PC           |             |             |                | instruction fetch |
| `ST1` | RS1/WB     | rs1 addr.    | instr. op.  |             |       ALU data | read register source 1 or upper immediate write-back |
| `ST2` | RS2/LD,EXE | rs2/ld addr. | rs1 data    | instr. op.  |                | read register source 2 or memory load, execute |
| `ST3` | ST/WB,EXE  | st/rd addr.  | rs2/ld data | rs1 data    | st/ld/ALU data | store or write-back destination register, execute |

If the [tightly coupled memory bus](../../../doc/Sysbus.md) is used,
then the ready signal can be used directly as a CPU stall,
simply as a state machine clock enable.
